Add optional `data` field to `SourceItem`
build-server-protocol/build-server-protocol pull request #692
Opened 2024-08-30 13:01 UTC by xuansontrinh

relevant discussion: https://github.com/build-server-protocol/build-server-protocol/discussions/691

2024-09-02 08:06 UTC, adpi2 approved these changes
LGTM

2024-09-02 13:34 UTC, agluszak requested changes

2024-09-02 13:34 UTC, agluszak commented on spec/src/main/resources/META-INF/smithy/bsp/extensions/jvm.smithy
> +    packageName: String
Please document it further. Is it supposed to always match the package declaration in the source file?

2024-09-02 13:34 UTC, agluszak commented
Also please add a changelog entry

2024-09-02 22:59 UTC, agluszak commented on spec/src/main/resources/META-INF/smithy/bsp/extensions/jvm.smithy
> +    /// if the source item is a file.
and if the source item is not a file? ;)

2024-09-04 10:58 UTC, agluszak approved these changes

2024-09-04 13:52 UTC, merged